[package]
name = "junzhu"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json", "blocking", "gzip"] }
tokio = { version = "1", features = ["full"] }
encoding_rs = "0.8"
regex = '1.10.5'
